### Submit answer
POST http://localhost:8000/submit-answer
Content-Type: application/json

# {
#   "session_id": "11932816-6bdb-48a9-801f-71783f425ca3",
#   "question_id": 2,
#   "answer": "Python basic data types include int, float, str, bool, and list. They differ in the type of data they store and how they behave."
# }

# Question 2
# {
#   "session_id": "11932816-6bdb-48a9-801f-71783f425ca3",
#   "question_id": 2,
#   "answer": "Expressions evaluate to a value, while statements perform an action. For example, `2 + 3` is an expression, `print(2+3)` is a statement."
# }

# Question 3
# {
#   "session_id": "11932816-6bdb-48a9-801f-71783f425ca3",
#   "question_id": 3,
#   "answer": "Indentation defines blocks of code in Python. Incorrect indentation leads to syntax errors or changes code logic."
# }

# Question 4
# {
#   "session_id": "11932816-6bdb-48a9-801f-71783f425ca3",
#   "question_id": 4,
#   "answer": "Python uses dynamic typing, which means variable types are determined at runtime. You can assign different types to the same variable."
# }

# Question 5
{
  "session_id": "8cce6120-7394-4904-833d-41b257bf30c4",
  "question_id": "q1",
  "answer": "Python's basic data types include int, float, str, bool, list, tuple, set, and dict. They differ in mutability, usage, and supported operations."
}